name: preview-provision
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]
jobs:
  harbor-provision:
    if: |
      github.event.pull_request.draft == false &&
      contains(github.event.pull_request.title, '[harbor]')
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Harbor via Composer
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Start Provisioning
        env:
          FORGE_DEPLOY_SCRIPT: ${{ vars.DEPLOY_SCRIPT }}
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: primavip.vip
        run: harbor provision
